#!/usr/bin/env node
/*
 * Writes audio-manifest.js — the small script index.html loads next to data.js
 * so it can tell, synchronously and without a network round trip, whether a
 * given Tigre string has a clip.
 *
 *   node tools/build_manifest.js
 *
 * The hashing functions are embedded from tools/tigre_audio.js rather than
 * copied by hand, so the browser can never disagree with the filenames on disk.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { tgNormalize, tgAudioId } = require("./tigre_audio.js");

const ROOT = path.join(__dirname, "..");
const AUDIO_DIR = path.join(ROOT, "audio");
const OUT = path.join(ROOT, "audio-manifest.js");

const present = fs.existsSync(AUDIO_DIR)
  ? fs.readdirSync(AUDIO_DIR).filter((f) => f.endsWith(".mp3")).map((f) => f.slice(0, -4))
  : [];
present.sort();

const worklist = JSON.parse(
  fs.readFileSync(path.join(__dirname, "tigre_strings.json"), "utf8")
);
const wanted = new Set(worklist.map((e) => e.id));
const missing = worklist.filter((e) => !present.includes(e.id));
const orphans = present.filter((id) => !wanted.has(id));

const body = `/*
 * AUTO-GENERATED by tools/build_manifest.js — do not edit.
 * ${present.length} clips. Regenerate with ./tools/render.sh
 */

const AUDIO_BASE = "audio/";

${tgNormalize.toString()}

${tgAudioId.toString()}

// Ids with a rendered clip. Lets the UI hide the speaker button rather than
// firing a request that 404s.
const AUDIO_SET = new Set(${JSON.stringify(present)});

function tgAudioSrc(text) {
  const id = tgAudioId(text);
  return AUDIO_SET.has(id) ? AUDIO_BASE + id + ".mp3" : null;
}
`;

fs.writeFileSync(OUT, body);
console.log(`${present.length} clips -> ${path.relative(ROOT, OUT)}`);

/*
 * Stamp the service worker with a version derived from the audio itself.
 *
 * Clip filenames are a hash of the Tigre text, not of the audio, so replacing
 * a clip's contents — synthesizing it again, or swapping in a recording —
 * leaves the URL identical. sw.js serves cache-first, so a browser that has
 * already played a word keeps its old copy forever and never sees the new one.
 * That is not theoretical: after recordings replaced the synthesized alphabet,
 * returning users still heard the synthetic voice.
 *
 * Hashing the set of clips means any change to the audio changes CACHE_NAME,
 * and the activate handler drops every cache that does not match it.
 */
const audioHash = crypto.createHash("sha1");
for (const id of present) {
  audioHash.update(id);
  audioHash.update(fs.readFileSync(path.join(AUDIO_DIR, id + ".mp3")));
}
const version = audioHash.digest("hex").slice(0, 8);

const SW = path.join(ROOT, "sw.js");
if (fs.existsSync(SW)) {
  const sw = fs.readFileSync(SW, "utf8");
  const updated = sw.replace(/const CACHE_NAME = "[^"]*";/,
                             `const CACHE_NAME = "lisan-tigrayit-${version}";`);
  if (updated !== sw) {
    fs.writeFileSync(SW, updated);
    console.log(`  service worker cache -> lisan-tigrayit-${version}`);
  }
}
if (missing.length) {
  console.log(`  ${missing.length} strings still without audio, first few:`);
  for (const e of missing.slice(0, 5)) console.log(`    ${e.id} ${JSON.stringify(e.text)}`);
}
if (orphans.length) console.log(`  ${orphans.length} clips no longer referenced by data.js`);
